### PR TITLE
Fixes for Warp 3.3

### LINKED ISSUE #15: Not working on Warp 3.3
It seems that due to the changes in Warp 3.3, `warp-grpc` is not working correctly. Most of the errors are about trailers:

```
$ grpcurl -v -plaintext -proto with-persistent.proto -d '{}' localhost:1234 withpersistent.PersistentService.onePerson

Resolved method descriptor:
rpc onePerson ( .google.protobuf.Empty ) returns ( .withpersistent.Person );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc+proto
date: Thu, 16 Jan 2020 11:52:38 GMT
server: Warp/3.3.6
trailer: grpc-status
trailer: grpc-message

Response trailers received:
(empty)
Sent 1 request and received 0 responses
ERROR:
  Code: Internal
  Message: server closed the stream without sending trailers
```

We need to investigate how to solve this, because otherwise `warp-grpc` cannot work with Stackage nightly.

### PR DESCRIPTION
**Pull request by serras**
The current way of handling trailers does not work on Warp 3.3. This PR fixes this, although the mechanism ended up being a bit complicated:

* Now it's mandatory to set the `TrailersMaker` before the body,
* But exceptions and problems may arise in the body, because that's where we obtain the messages,
* The solution was to introduce an `IORef`, initially set at `OK`, but which is updated when one calls `modifyGRPCStatus`.

In order to support both Warp < 3.3 and Warp >= 3.3, I've left the code for the former.

Fixes #15

### CODE REVIEW

**Comment by serras** [comment]
@lucasdicioccio could we release this soon? This is blocking us for https://github.com/higherkindness/mu-haskell/issues/85. I would push the change myself to Hackage, but I'm not sure I'm in the uploaders group for `warp-grpc`.

**Comment by lucasdicioccio** [comment]
I'll have a look (home life is pretty busy these days) thanks for the PR.
As far as I remember you should be maintainer on `warp-grpc`

File: warp-grpc/src/Network/GRPC/Server/Handlers.hs [hunk 1]
```diff
@@ -295,4 +296,4 @@ handleRequestChunksLoop decoder handleMsg handleEof nextChunk =
 errorOnLeftOver :: (a -> IO b) -> ByteString -> a -> IO b
 errorOnLeftOver f rest
   | ByteString.null rest = f
-  | otherwise            = const $ closeEarly $ GRPCStatus INVALID_ARGUMENT ("left-overs: " <> rest)
+  | otherwise            = const $ putStrLn "left-over" >> closeEarly (GRPCStatus INVALID_ARGUMENT ("left-overs: " <> rest))
```
Comment (lucasdicioccio) [inline warp-grpc/src/Network/GRPC/Server/Handlers.hs]: I'm parted in leaving the `putStrLn` here. I agree we should see it rarely so it shouldn't matter. Maybe add a longer message like `warp-grpc: left-overs bytes while parsing messages`.

**Comment by lucasdicioccio** [comment]
LGTM.

**Comment by lucasdicioccio** [comment]
I'm re-running the failed check (with a merge commit) because apparently the error log is `null`. If it still fails I'll be happy enough with the branch check.

File: warp-grpc/src/Network/GRPC/Server/Handlers.hs (hunk 1 above)
Comment (lucasdicioccio) [reply warp-grpc/src/Network/GRPC/Server/Handlers.hs]: Let's merge as is and we'll do a minor patch release if some complain.

**Comment by lucasdicioccio** [comment]
https://hackage.haskell.org/package/warp-grpc-0.3.0.0

**Comment by serras** [comment]
Thanks for uploading and reviewing it! :)
